FROM node:22-alpine
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY . .
ENV PORT=3000
ENV AWS_LWA_READINESS_CHECK_PATH=/api/products
EXPOSE 3000
CMD ["node", "server.js"]